services:
  database:
    image: mariadb:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks: 
      - trincachallenge2

  cacher:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    networks: 
      - trincachallenge2

  trincachallenge2:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - NODE_ENV=${NODE_ENV}
    image: node:slim
    volumes:
      - type: bind
        source: ./
        target: /opt/trincachallenge2
    container_name: trincachallenge2
    depends_on: 
      - database
      - cacher
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    networks: 
      - trincachallenge2

volumes:
  trincachallenge2:

networks:
  trincachallenge2:
    ipam:
      driver: default
      config:
        - subnet: 10.172.170.0/24