services:
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    networks: 
      - node
    
  trincachallenge2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node:slim
    container_name: trincachallenge2
    depends_on: 
      - redis
    ports: 
      - "3333:3333"
    env_file:
      - ./.env
    networks: 
      - node

networks:
  node:
    ipam:
      driver: default
      config:
        - subnet: 10.172.170.0/24