@protocol = http
@domain = localhost
@port =  3333
@host = {{protocol}}://{{domain}}:{{port}}
##############################################################
# @name login
POST {{host}}/login
Content-Type: application/json

{
    "email": "nitaicharan@gmail.com",
    "password": "123"
}
##############################################################
POST {{host}}/refresh-token
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "refresh_token": "{{login.response.body.refresh_token}}"
}