@protocol = http
@domain = localhost
@port =  3333
@host = {{protocol}}://{{domain}}:{{port}}
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYTA3ZjVhODEtMGY0MC00MDU1LWE3OTUtZTZjM2VhZjYzOWZhIiwiaWF0IjoxNjI4ODIxMTI3LCJleHAiOjE2Mjg5MDc1Mjd9.Ph5ksld-xfi2_8w3lL-s-fyO1ivPq-4RYnz-UDR2t5Y
##############################################################
GET {{host}}/barbecues
Authorization: {{authorization}}
##############################################################
GET {{host}}/barbecues/{{create_entity.response.body.id}}
Authorization: {{authorization}}
##############################################################
# @name create_entity
POST {{host}}/barbecues
Content-Type: application/json
Authorization: {{authorization}}

{
    "description": "description",
    "price": "100"
}
##############################################################
PATCH  {{host}}/barbecues/{{create_entity.response.body.id}}/sign-user
Content-Type: application/json
Authorization: {{authorization}}

{
    "user_id": "a07f5a81-0f40-4055-a795-e6c3eaf639fa"
}