@protocol = http
@domain = localhost
@port =  3333
@host = {{protocol}}://{{domain}}:{{port}}
##############################################################
GET {{host}}/barbecues
##############################################################
GET {{host}}/barbecues/{{create_entity.response.body.id}}
##############################################################
# @name create_entity
POST {{host}}/barbecues
Content-Type: application/json

{
    "description": "description",
    "price": "100"
}
##############################################################
PATCH  {{host}}/barbecues/{{create_entity.response.body.id}}/sign-user
Content-Type: application/json

{
    "user_id": "69593bc4-6874-4823-af4a-6a6dfaa25305"
}