@protocol = http
@domain = localhost
@port =  3333
@host = {{protocol}}://{{domain}}:{{port}}
##############################################################
GET {{host}}/barbecues
##############################################################
GET {{host}}/barbecues/{{create_entity.response.body.id}}
##############################################################
# @name create_entity
POST {{host}}/barbecues
Content-Type: application/json

{
    "description": "description",
    "price": "1000"
}