@protocol = http
@domain = localhost
@port =  3333
@host = {{protocol}}://{{domain}}:{{port}}
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGQ2Yjk3MWQtMDhkMC00ZTAyLTk5OTMtOWFlZGM1NmRlM2FkIiwiaWF0IjoxNjI4ODE5MTU2LCJleHAiOjE2Mjg5MDU1NTZ9.36oanSB7Q-Gj-NDn8l4VWsH1cnDw6ZYnXtW_MoVAs4Y
##############################################################
GET {{host}}/users
Authorization: {{authorization}}
##############################################################
POST {{host}}/users
Content-Type: application/json

{
    "name": "Nitai Charan",
    "email": "nitaicharan@gmail.com",
    "password": "123"
}